version: "3.8"

services:
  quarkus-app:
    build:
      dockerfile: ./com.example.usermicroservice/Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005" # Debugging port
    working_dir: /code
    entrypoint: [ "mvn", "clean", "quarkus:dev" ]
    volumes:
      - ./com.example.usermicroservice:/code
    container_name: usermicroservice
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: sua_senha
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/seubanco
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-usermicroservice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: seubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres-data:


